"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PAGINATION = exports.MAGIC_LINK = exports.FILE_UPLOAD = exports.OFFER = exports.INTERVIEW = exports.JOB_OPENING = exports.CANDIDATE = exports.AUTH = void 0;
exports.AUTH = {
    EMAIL_MAX_LENGTH: 254,
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 128,
    SESSION_MAX_HOURS: 8,
    MAX_LOGIN_ATTEMPTS: 5,
    LOCKOUT_MINUTES: 15,
    RATE_LIMIT_REQUESTS: 10,
    RATE_LIMIT_WINDOW_SECONDS: 60,
};
exports.CANDIDATE = {
    NAME_MAX_LENGTH: 100,
    EMAIL_MAX_LENGTH: 254,
    PHONE_MAX_LENGTH: 20,
    LOCATION_MAX_LENGTH: 100,
    CURRENT_ROLE_MAX_LENGTH: 100,
    NOTICE_PERIOD_MAX_LENGTH: 50,
    SALARY_EXPECTATION_MAX_LENGTH: 50,
    LINKEDIN_URL_MAX_LENGTH: 255,
    REJECTION_REASON_MIN_LENGTH: 5,
    REJECTION_REASON_MAX_LENGTH: 500,
};
exports.JOB_OPENING = {
    TITLE_MAX_LENGTH: 200,
    DESCRIPTION_MAX_LENGTH: 5000,
    SKILLS_MIN_COUNT: 1,
    SKILLS_MAX_COUNT: 20,
    SKILL_TAG_MAX_LENGTH: 50,
};
exports.INTERVIEW = {
    INTERVIEWER_NAME_MAX_LENGTH: 100,
    NOTES_MAX_LENGTH: 1000,
    FEEDBACK_MIN_LENGTH: 1,
    FEEDBACK_MAX_LENGTH: 2000,
};
exports.OFFER = {
    SALARY_MIN: 0.01,
    SALARY_MAX: 9_999_999.99,
    SALARY_DECIMAL_PLACES: 2,
};
exports.FILE_UPLOAD = {
    MAX_SIZE_BYTES: 10 * 1024 * 1024,
    ALLOWED_MIME_TYPES: ['application/pdf'],
};
exports.MAGIC_LINK = {
    EXPIRY_DAYS: 14,
    TOKEN_BYTES: 32,
};
exports.PAGINATION = {
    DEFAULT_PAGE_SIZE: 20,
    SEARCH_MIN_LENGTH: 2,
    SEARCH_MAX_LENGTH: 100,
    SEARCH_DEBOUNCE_MS: 300,
    TIMELINE_MAX_EVENTS: 50,
};
//# sourceMappingURL=limits.js.map