export { emailSchema } from './email';
export type { ValidationResult } from './email';
export { phoneSchema } from './phone';
export { salaryAmountSchema, currencySchema, salaryInputSchema } from './salary';
export type { SalaryInput } from './salary';
export { linkedinUrlSchema, optionalLinkedinUrlSchema } from './linkedin';
export { jobTitleSchema, skillsTagsSchema } from './job';
export { candidateNameSchema, rejectionReasonSchema } from './candidate';
export { interviewNotesSchema, feedbackSchema, interviewerNameSchema } from './interview';
export { passwordSchema, loginFormSchema } from './auth';
export type { LoginFormInput } from './auth';
import { z } from 'zod';
export declare const reportingManagerSchema: z.ZodString;
export declare const locationSchema: z.ZodString;
export declare const searchQuerySchema: z.ZodString;
